import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import { Layout } from '@shopify/polaris'

import Header from 'src/components/header'
import Menu from 'src/components/Menu'

export default function AppHome({Components, pageProps}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next Shopify App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header />
            <div className="content container">
            <Layout>
                <nav className="navigation">
                <Layout.Section secondary>
                    <Menu />
                </Layout.Section>
                </nav>
                <Layout.Section>
                    {/* <Components {...pageProps} /> */}
                </Layout.Section>
            </Layout>
            </div>
        </div>
    )
}
