import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import { AppProvider, Layout, Frame } from '@shopify/polaris'
import { LiveChatLoaderProvider } from "react-live-chat-loader";
import translations from "@shopify/polaris/locales/en.json";

import Header from 'src/components/header'
import Menu from 'src/components/Menu'

export default function AppHome({Components, pageProps}) {
    return (        
        <AppProvider i18n={translations}>
            <Frame>
                <Head>
                    <title>Create Next Shopify App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Header />
                <div className="content container">
                <Layout>
                    <nav className="navigation">
                    <Layout.Section secondary>
                        <Menu />
                    </Layout.Section>
                    </nav>
                    <Layout.Section>
                        {/* <Components {...pageProps} /> */}
                    </Layout.Section>
                </Layout>
                </div>
            </Frame>
        </AppProvider>
    )
}
